import { test, expect } from '@playwright/test'
test("api modele tarif carburant autre clio-v work!", async ({ request }) => {
    let response = await request.get(`https://entreprise.elite-auto.fr/api/model/redirection/1/7368/renault-clio-v-societe`)
    expect(response.status()).toBe(200)
    const res = await response.json()
    expect(typeof (res.isUtilitaire)).toBe("boolean")
    expect(typeof (res.toRedirect)).toBe("boolean")
    expect(typeof (res.isEnabled)).toBe("boolean")
    expect(res.marque).toContain("renault")
    expect(res.newSlug).toBe("clio-v-societe")
})
test("api modele entreprise finition footer work!", async ({ request }) => {
    let response = await request.get(`https://entreprise.elite-auto.fr/api/marque/ventevoiturefooter/7368/marque_modele_offres_finition_utility/modele`)
    expect(response.status()).toBe(200)
    const res = await response.json()
    expect(res.linksBas.length).toBe(8)
})
test("api modele tarif carburant diesel menugauche work!", async ({ request }) => {

    let response = await request.get(`https://entreprise.elite-auto.fr/api/marque/menugauche/1/utility/7368`)
    expect(response.status()).toBe(200)
    const res = await response.json()
    expect(parseInt(res.marqueId)).toBe(1)
    expect(res.marqueName).toEqual(`Renault`)
    res.menuTab.forEach(menu => {
        const menuTabObj = Object.keys(menu)
        expect(menuTabObj).toContain("title")
        expect(menuTabObj).toContain("url")
        let titleParams = menu.title
        expect(titleParams).toContain("Renault")
        let urlParams = menu.url
        expect(urlParams).toContain(`renault`)
    })
})
test("api modele entreprise finition textrefs air-blue work!", async ({ request }) => {
    let response = await request.get(`/api/model/textrefs/1/7368/marque_modele_offres_finition_utility/finition/air-blue`)
    expect(response.status()).toBe(200)
    const res = await response.json()
    expect(res.type).toContain("marque_modele_offres_finition_utility")
    expect(res.mark).toContain("Renault")
    expect(res.markId).toBe(1)
    expect(res.model).toContain("CLIO V SOCIETE")
    expect(res.model_nom_compl).toContain("CLIO V SOCIETE")
    expect(res.nomSinguilier).toContain("UTILITAIRE")
    expect(res.modelId).toBe(2721)
    expect(res.modelVnUrl).toContain("/voiture-renault-1/clio-v-societe-7368.html")
    expect(res.img).toContain("/visuel/modeles/600x400/renault_clio_2019.png")
    expect(res.image).toContain("/images/logos/marques/logo_renault_new.png")
    expect(res.imageLink).toContain("/voiture-renault-1.html")
    expect(res.title).toContain("Utilitaire Renault Clio v societe Air blue")
    const menuObj = Object.keys(res.menu[0])
    expect(menuObj).toContain("text")
    expect(menuObj).toContain("url")
    expect(res.textTop).toContain("<h2> Véhicule entreprise renault clio v societe Air blue</h2><p> Votre utilitaire Renault CLIO V SOCIETE en finition Air blue est vendu neuf avec une remise de")
    expect(res.textMiddle).toBeNull()
    expect(res.subtexttop).toBeNull()
    expect(res.resume).toContain("<p><h2>Les équipements de la renault clio v societe Air blue</h2><p></p></p>")
    const listeEkomiObj = Object.keys(res.listeEkomi[0])
    expect(listeEkomiObj).toContain("rate")
    expect(listeEkomiObj).toContain("review")
    expect(listeEkomiObj).toContain("reviewDate")
})
test("api modele entreprise finition referencement work!", async ({ request }) => {
    let response = await request.get(`https://entreprise.elite-auto.fr/api/model/referencement/1/7368/marque_modele_offres_finition_utility/finition/air-blue`)
    expect(response.status()).toBe(200)
    const res = await response.json()
    expect(res.title).toContain("Renault Clio v societe Air blue")
    expect(res.description).toContain("Utilitaire Renault CLIO V SOCIETE Air blue :")
})
test("api modele entreprise finition filter groupe work!", async ({ request }) => {
    let response = await request.get(`https://entreprise.elite-auto.fr/api/filter/groupe-of-model/7368`)
    expect(response.status()).toBe(200)
    const res = await response.json()
    expect(res.groupe).toContain("CLIO")
})
test("api modele entreprise finition tag-schema work!", async ({ request }) => {
    let response = await request.get(`https://entreprise.elite-auto.fr/api/model/tag-schema/1/7368/marque_modele_offres_finition_utility/null/finition/air-blue`)
    expect(response.status()).toBe(200)
    const res = await response.json()
    expect(res).toContain("<script ")
})
test("api modele entreprise finition tag-google work!", async ({ request }) => {
    let response = await request.get(`https://entreprise.elite-auto.fr/api/model/tag-google/1/7368/marque_modele_offres_finition_utility/finition/air-blue`)
    expect(response.status()).toBe(200)
    const res = await response.json()
    expect(res).toContain("<script>")
})
test("api modele VN finition work!", async ({ request }) => {

    let response = await request.get(`https://entreprise.elite-auto.fr/api/filter/v2/finition?models=%22CLIO%22`)
    expect(response.status()).toBe(200)
    const res = await response.json()
    const finitionObj = Object.keys(res[0])
    expect(finitionObj).toContain('finition')
})