import { test, expect } from '@playwright/test'
test("api modele entreprise finition textrefs air-blue work!", async ({ request }) => {
    let response = await request.get(`https://entreprise.elite-auto.fr/api/model/textrefs/1/7368/marque_modele_offres_motorisation_utility/motorisation/clio-societe-dci-85`)
    expect(response.status()).toBe(200)
    const res = await response.json()
    expect(res.type).toContain("marque_modele_offres_motorisation_utility")
    expect(res.mark).toContain("Renault")
    expect(res.markId).toBe(1)
    expect(res.model).toContain("CLIO V SOCIETE")
    expect(res.model_nom_compl).toContain("CLIO V SOCIETE")
    expect(res.nomSinguilier).toContain("UTILITAIRE")
    expect(res.modelId).toBe(2721)
    expect(res.modelVnUrl).toContain("/voiture-renault-1/clio-v-societe-7368.html")
    expect(res.img).toContain("/visuel/modeles/600x400/renault_clio_2019.png")
    expect(res.image).toContain("/images/logos/marques/logo_renault_new.png")
    expect(res.imageLink).toContain("/voiture-renault-1.html")
    expect(res.title).toContain("Utilitaire Renault Clio v societe Clio societe dci 85")
    const menuObj = Object.keys(res.menu[0])
    expect(menuObj).toContain("text")
    expect(menuObj).toContain("url")
    expect(res.textTop).toContain(" Véhicule entreprise renault clio v societe Clio societe dci 85</h2><p> Votre utilitaire Renault CLIO V SOCIETE en motorisation Clio societe dci 85 est vendu neuf avec une remise de")
    expect(res.textMiddle).toBeNull()
    expect(res.subtexttop).toBeNull()
    expect(res.resume).toBeNull()
    const listeEkomiObj = Object.keys(res.listeEkomi[0])
    expect(listeEkomiObj).toContain("rate")
    expect(listeEkomiObj).toContain("review")
    expect(listeEkomiObj).toContain("reviewDate")
})
test("api modele entreprise finition referencement work!", async ({ request }) => {
    let response = await request.get(`https://entreprise.elite-auto.fr/api/model/referencement/1/7368/marque_modele_offres_motorisation_utility/motorisation/clio-societe-dci-85`)
    expect(response.status()).toBe(200)
    const res = await response.json()
    expect(res.title).toContain("Renault Clio v societe Clio societe dci 85")
    expect(res.description).toContain("Utilitaire Renault CLIO V SOCIETE Clio societe dci 85 :")
})
test("api modele entreprise moteur tag-schema work", async ({ request }) => {
    let response = await request.get(`https://entreprise.elite-auto.fr/api/model/tag-schema/1/7368/marque_modele_offres_motorisation_utility/null/motorisation/clio-societe-dci-85`)
    expect(response.status()).toBe(200)
    const res = await response.json()
    expect(res).toContain("<script ")

})
test("api modele entreprise moteur tag-google work!", async ({ request }) => {
    let response = await request.get(`https://entreprise.elite-auto.fr/api/model/tag-google/1/7368/marque_modele_offres_motorisation_utility/motorisation/clio-societe-dci-85`)
    expect(response.status()).toBe(200)
    const res = await response.json()
    expect(res).toContain("<script>")

})
test("api modele entreprise moteur footer work!", async ({ request }) => {
    let response = await request.get(`https://entreprise.elite-auto.fr/api/marque/ventevoiturefooter/7368/marque_modele_offres_motorisation_utility/modele`)
    expect(response.status()).toBe(200)
    const res = await response.json()
    expect(res.linksBas.length).toBe(8)

})
test("api modele entreprise moteur filter motorisation work!", async ({ request }) => {

    let response = await request.get(`https://entreprise.elite-auto.fr/api/filter/v2/motorisation?models=%22CLIO%22`)
    expect(response.status()).toBe(200)
    const res = await response.json()
    const motorisationObj = Object.keys(res[0])
    expect(motorisationObj).toContain("motorisation")
})