version: '3.3'

services: 
# Service nginx  
  nginx:
    image: registry.gitlab.com/elite-auto/elite-auto/nginx:prerelease
    ports:
      - "80:80"
    environment: 
      - ENV=${ENV}
      - WWW_EA_HOST=${WWW_EA_HOST}
      - LEASING_EA_HOST=${LEASING_EA_HOST}
      - UTILITAIRE_EA_HOST=${UTILITAIRE_EA_HOST}
    depends_on:
      - client
    networks: 
        - elite 

  # Service client    
  client:
    image: registry.gitlab.com/elite-auto/elite-auto/client:prerelease
    tty: true
    ports:
      - "4000:4000"
    networks: 
        - elite

# image proxy service
  image-proxy:
    image: registry.gitlab.com/elite-auto/elite-auto/imgproxy:prerelease
    restart: on-failure
    networks: 
      - elite 


networks:
    elite:
        driver: bridge
